GET http://localhost:8080/api/posts

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Last Post"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
"id": 0,
"content": "New Post"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "New New Post"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
"id": 2,
"content": "New 2 Post"
}

###

DELETE http://localhost:8080/api/posts/3
Content-Type: application/json

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 8,
  "content": "New 8 Post"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 3,
  "content": "New 3 Post"
}